# Rare hybridization detected between two sympatric Ranid frog species in the northern Sierra Nevada, California {#hybrids}

<!-- Required to number equations in HTML files -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

## Introduction

Landscape changes can influence species demography and migration patterns (Li et al. 2017) by changing rates of gene flow within species. Changing migration rates and population sizes can influence population structure, thus over time, landscape changes can affect significant change in a species. Furthermore, cross-breeding or hybridization between closely related taxa can promote gene flow (introgression) between species, which may be an important evolutionary mechanism for either homogenization (reversing initial divergence between species) or reproductive isolation (potentially leading to speciation)(Mallet 2007, Barrera-Guzmán et al. 2018).
Hybridization events in vertebrates may be rare, or rarely detected, and thus identifying potential hybridization can be difficult and may be affected by sampling design, timing, and resolution of genetic markers. Therefore, occurrences of hybridization likely remain unknown, particularly in cryptic taxa. Assessing population admixture or detecting potential hybridization has previously been challenging; however,  modern genetic methods provide a powerful approach to assess populations at fine geographic and evolutionary scales(Ali et al. 2016, Prince et al. 2017).
We investigate the potential for hybridization in two sympatrically occurring endemic frog species in the Sierra Nevada of California, USA. Foothill yellow-legged frogs, Rana boylii, (Baird 1856) historically occurred in lower and mid-elevation (< 1500 m) streams and rivers from Southern Oregon to northern Baja California west of the Sierra-Cascade crest (Stebbins 2003), whereas Sierra Nevada yellow-legged frogs, Rana sierrae, (Camp 1917) typically occur from 1500 m to over 3600 m in lakes and streams (Stebbins 2003). Population declines have been documented across the former range of both of these species; R. sierrae has been extirpated from over 90 percent of its historical range (Drost and Fellers 1996, Vredenburg et al. 2007) while R. boylii has been extirpated from 50 percent of its historical range (Jennings and Hayes 1994, Davidson et al. 2002). Both species are species of conservation concern; in 2014, the U. S. Fish and Wildlife Service (USFWS) listed R. sierrae as endangered under the U. S. Endangered Species Act (ESA)(USFWS 2014), and R. boylii is a state species of special concern and a candidate for listing under state and federal ESA. 
Unlike other ranid frog species with broad areas of potential intergradation (Shaffer et al. 2004), R. boylii and R. sierrae only rarely occur sympatrically. Zweifel (1955) described one historical location where these two species co-occurred, in Butte County near DeSabla.  Currently the only known locations where both species are found are in several tributaries to the Feather River in the northern Sierra Nevada, California (Figure 1). Hybridization between these species has not previously been successfully documented—breeding experiments by Zwiefel (1955) between R. sierrae (formerly known as R. muscosa) and R. boylii yielded very low viability and high incidences of embryological abnormalities—likely indicating a post-zygotic barrier between the species. However, these experiments only crossed female R. sierrae individuals with male R. boylii, and the individuals were from very different California regions (e.g., Butte and Nevada County vs. Contra Costa County).
R. boylii and R. sierrae can have very similar morphology and habitat preferences in areas they co-occur, thus assigning individuals to species is difficult and imprecise using field identification methods. This presents a challenge for management because these sympatric species have different conservation status and management objectives.  In cases where hybridization is present, conservation actions must consider whether hybridization may lead to reproductive isolation (Barrera-Guzmán et al. 2018b).
We employed modern genetic methodology to better understand the evolutionary history of R. sierrae and R. boylii where their ranges overlap.  We investigated three primary questions: 

  1.	Can hybridization be detected between two sympatrically occurring threatened and endangered (ESA) frog species in the Sierra Nevada using data generated from genome-wide single nucleotide polymorphisms (SNPs);
  2.	If hybrids can be detected, do genetic signatures suggest hybrid viability; 
  3.	Using coalescent modeling, are migration rates between species in sympatrically occurring populations higher than in allopatrically occurring populations in adjacent watersheds?

## Chemistry 101: Symbols

Chemical formulas will look best if they are not italicized. Get around math mode's automatic italicizing in LaTeX by using the argument `$\mathrm{formula here}$`, with your formula inside the curly brackets.  (Notice the use of the backticks here which enclose text that acts as code.)

So, $\mathrm{Fe_2^{2+}Cr_2O_4}$ is written `$\mathrm{Fe_2^{2+}Cr_2O_4}$`.

<!--
The \noindent command below does what you'd expect:  it forces the current line/paragraph to not indent. This was done here to match the format of the LaTeX thesis PDF.
-->

\noindent Exponent or Superscript: $\mathrm{O^-}$

\noindent Subscript: $\mathrm{CH_4}$

To stack numbers or letters as in $\mathrm{Fe_2^{2+}}$, the subscript is defined first, and then the superscript is defined.

\noindent Bullet: CuCl $\bullet$ $\mathrm{7H_{2}O}$


\noindent Delta: $\Delta$

\noindent Reaction Arrows: $\longrightarrow$ or  $\xrightarrow{solution}$

\noindent Resonance Arrows: $\leftrightarrow$

\noindent Reversible Reaction Arrows: $\rightleftharpoons$

### Typesetting reactions

You may wish to put your reaction in an equation environment, which means that LaTeX will place the reaction where it fits and will number the equations for you. 

\begin{equation}
  \mathrm{C_6H_{12}O_6  + 6O_2} \longrightarrow \mathrm{6CO_2 + 6H_2O}
  (\#eq:reaction)
\end{equation}

We can reference this combustion of glucose reaction via Equation \@ref(eq:reaction).

### Other examples of reactions

$\mathrm{NH_4Cl_{(s)}}$ $\rightleftharpoons$ $\mathrm{NH_{3(g)}+HCl_{(g)}}$

\noindent $\mathrm{MeCH_2Br + Mg}$ $\xrightarrow[below]{above}$ $\mathrm{MeCH_2\bullet Mg \bullet Br}$

## Physics

Many of the symbols you will need can be found on the math page <http://web.reed.edu/cis/help/latex/math.html> and the Comprehensive LaTeX Symbol Guide (<http://mirror.utexas.edu/ctan/info/symbols/comprehensive/symbols-letter.pdf>).

## Biology

You will probably find the resources at <http://www.lecb.ncifcrf.gov/~toms/latex.html> helpful, particularly the links to bsts for various journals. You may also be interested in TeXShade for nucleotide typesetting (<http://homepages.uni-tuebingen.de/beitz/txe.html>).  Be sure to read the proceeding chapter on graphics and tables.

