---
output: pdf_document
---

**Abstract**

*Rana boylii* is an imperiled frog species native to CA and OR, and it is currently designated as a species of special concern (CDFW) in the state of CA. It has been petitioned as candidate for federal (USFWS) and state (CDFW) listing. As a lotic breeding amphibian, *R. boylii* is tied closely to the local hydrology within the watersheds it inhabits. It is particularly sensitive to alterations to flow regimes. Future conservation of this species requires several crucial components, including establishing higher resolution watershed-level boundaries for populations across the species range,  delineation of distinct population segments that can be utilized in conservation management, and quantification of relative genomic health of these groups (i.e., genomic diversity,  measures of isolation, connectivity). We provide data on over 700 samples across the range of the species, identify six genomically distinct groups, as well as subdivision at local watershed scales. These data are congruent with other molecular data on *R. boylii*, although we identify and add individuals from the Feather watershed as a distinctive group, at both population and subpopulation scales. Quantification and comparison of genomic variation across populations indicates populations in the southern coast, southern Sierra Nevada, and Northern Sierra/Feather basin in California should have high prioritization in conservation efforts due to patterns of bottlenecking and low genomic diversity.    One major impact on *R. boylii* populations has been river regulation, or the hydrological alteration of flow by dams and diversions. River regulation has been implicated as a cause of fundamental changes to downstream aquatic ecosystems. Regulation changes the natural flow regime which may restrict population connectivity and decrease genetic diversity in some species. Since population connectivity and the maintenance of genetic diversity are fundamental drivers of long-term persistence, understanding the extent that river regulation impacts these critical attributes of genetic health is an important goal. Foothill yellow-legged frog (FYLF; *Rana boylii*) were historically abundant throughout many western rivers but have declined since the onset of regulation. However, the extent to which FYLF populations in regulated rivers are maintaining connectivity and genetic diversity is unknown. Here we use genetic methods to investigate the impacts of river regulation on FYLF to explore their potential for long-term persistence under continued regulation. We found FYLF in regulated rivers showed striking patterns of isolation and trajectories of genetic diversity loss relative to unregulated rivers. For example, river regulation explained the greatest amount of variance in population genetic differentiation compared with other covariates including geographic distance. Importantly, patterns of connectivity and genetic diversity loss were observed regardless of regulation level but were most prominent in locations with the greatest regulation intensity. Although our results do not bode well for long-term persistence of FYLF populations under current flow regulation regimes, they do highlight the power of genetic monitoring for assessing population health in aquatic organisms.    In addition, analyses of data on hybridization between *R. boylii* and *R. sierrae* in a single region of the Sierra Nevada of California is shown. Cross-breeding between species, or hybridization in vertebrates has generally been considered a rare occurrence. Hybridization between species may combine parental genotypes in ways that yield reproductively sterile or isolated lineages, and hybridization events may be short-lived and difficult to detect. Furthermore, cross-breeding or hybridization between closely related taxa can promote gene flow (introgression) between species, which may be an important evolutionary mechanism for either homogenization (reversing initial divergence between species) or reproductive isolation (potentially leading to speciation). Here, we used thousands of genetic markers from nuclear DNA to detect a very rare hybridization event between two co-occurring frog species (*R. boylii* and *R. sierrae*) in the Sierra Nevada of California. Hybridization events are rare but have occurred in the Feather drainage between these two species, however it appears these are terminal events based on PCA, admixture, and tests of heterozygosity in species diagnostic SNPs.

<!-- This code does not include the preliminary pages so I hard coded it -->
<!-- \hspace{10.5 cm} (\pageref{LastPage} pages) -->

